config/routes.rb
  Rails.application.routes.draw do
  devise_for :users
  resources :orders, only: [:new, :index, :create, :show]
  resources :carts, only: [:show]

  resources :cart_items, only: [:create, :update, :destroy]

  resources :reviews
  root 'page#index'

  namespace :admin do
    resources :users
    resources :products
    resources :orders
  end

  resources :users, only: [:index, :new, :create, :show]
  resources :page, only: [:index, :post]

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # if a cart is destroyed the all the cart_items in it get destroyed as well
  has_many :cart_items, dependent: :destroy
  belongs_to :user
  # has_many :products, :through => :cart_items
  # has_and_belongs_to_many :products

  # method to empty current_cart when user submits to order
  def empty!
    self.cart_items.each do |item|
      item.cart_id = nil
      item.save!
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  helper_method :subtotal, :cartEmpty?

  def show
    # application controller method to find shopping cart
    @cart = current_cart
    @cart_items = @cart.cart_items.order(:id);
    @products = @cart_items.product;
    @user = User.find(@cart.users_id)
  end

  def subtotal
    cart_items.collect {|cart_items| cart_items.valid? ? (cart_items.quantity * cart_items.unit_price) : 0}.sum
  end


  private

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<!--subtotal variable -->
<%subtotal =@cart_items.collect {|item| item.quantity*item.unit_price}.sum%>
<!--subtotal + shipping cost  -->
<%total=subtotal+15%>
<div class="totals">
  <div class="totals-item">
    <label>Subtotal</label>
    <div class="totals-value" id="cart-subtotal"><%=subtotal%></div>
  </div>
  <div class="totals-item">
    <label>Tax (5%)</label>
    <div class="totals-value" id="cart-tax">Included!</div>
  </div>
  <div class="totals-item">
    <label>Shipping</label>
    <div class="totals-value" id="cart-shipping">15.00</div>
  </div>
  <div class="totals-item totals-item-total">
    <label>Grand Total</label>
    <div class="totals-value" id="cart-total">
      <%=total%>
    </div></div>
  </div>
</div>
    <button class="checkout">Checkout</button>

app/views/carts/_carts_row.html.erb
<h1>Shopping Cart</h1>

<div class="shopping-cart">
  <div class="column-labels">
    <label class="product-image">Image</label>
    <label class="product-details">Product</label>
    <label class="product-price">Price</label>
    <label class="product-quantity">Quantity</label>

    <!-- adding update column to labels -->
    <label class="product-update">Update</label>
    <label class="product-removal">Remove</label>
    <label class="product-line-price">Total</label>
  </div>

  <br />
  <br />
  <br />
  <%if @cart.cart_items.size == 0%>
  <div class="text-center" style="margin-top: 100px;">
    <p>Looks like you have nothing in your cart! <%=link_to 'Add something to your cart', products_path%></p>
  </div>
  <%end%>

  <br />
  <br />
  <%if !@cart_items.empty? %>
    <%@cart_items.each do |item|%>

    <div class="product">
      <div class="product-image">
        <%=image_tag(item.product.picture.thumb)%>
      </div>
      <div class="product-details">
        <div class="product-title"><%=item.product.name%></div>
        <p class="product-description"><%=item.product.description%></p>
      </div>
      <div class="product-price"><%=number_to_currency(item.product.price)%></div>

      <%=form_for item, remote: true do |f|%>
      <div class="product-quantity">
        <%=f.number_field :quantity, value: item.quantity, min: 1, max: 8%>
        <%=f.hidden_field :product_id, value: item.product.id%>
      </div>
      <div class="product-update">
        <%=f.submit 'Update', class: "update-product"%>
      </div>
      <%end%>
      <div class="product-removal">
        <%= button_to "Remove", item, {data: {confirm: "Are you sure you wish to remove '#{item.product.name}' from your cart?"}, method: :delete, remote: true, class: "remove-product"}%>
      </div>
      <div class="product-line-price"><%=number_to_currency(item.product.price*item.quantity)%></div>
    </div>

  <%end%>
<%end%>
<br />
<br />

<!--Temporary solution until model methods are written  -->
<% if !@cart_items.empty? %>
  <!--subtotal variable -->
  <%subtotal =@cart_items.collect {|item| item.quantity*item.unit_price}.sum%>
  <!--subtotal + shipping cost  -->
  <%total=subtotal+15%>
<div class="totals">
  <div class="totals-item">
    <label>Subtotal</label>
    <div class="totals-value" id="cart-subtotal"><%=number_to_currency(subtotal)%></div>
  </div>
  <div class="totals-item">
    <label>Tax (5%)</label>
    <div class="totals-value" id="cart-tax">Included!</div>
  </div>
  <div class="totals-item">
    <label>Shipping</label>
    <div class="totals-value" id="cart-shipping"><%=number_to_currency(15.00)%></div>
  </div>
  <div class="totals-item totals-item-total">
    <label>Grand Total</label>
    <div class="totals-value" id="cart-total">
      <%=number_to_currency(total)%>
    </div></div>
  </div>
</div>
<!--end shopping cart -->

<div class="checkout-btn">
  <button class="checkout" data-toggle="modal" data-target="#checkout-modal">Checkout</button>
</div>

<div class="modal fade" id="checkout-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Checkout Summary</h4>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row">
            <p class="col-md-2 col-xs-3 col-md-offset-0">
              <u>Product Name</u>
            </p>

            <p class="col-md-2 col-xs-1 col-md-offset-0 col-xs-offset-2">
              <u>Price</u>
            </p>
            <p class="col-md-2 col-xs-1 col-md-offset-0 col-xs-offset-2">
              <u>Quantity</u>
            </p>
          </div>
        <%@cart_items.each do |item|%>

        <div class="row">
          <div class="col-md-2 col-xs-3 col-md-offset-0">
          <p>
            <%=item.product.name%>
          </p>
          </div>
          <div class="col-md-2 col-xs-1 col-md-offset-0 col-xs-offset-2">
            <%=number_to_currency(item.product.price)%>
          </div>
          <div class="col-md-2 col-xs-1 col-md-offset-0 col-xs-offset-2">
            <p><%=item.quantity%></p>
          </div>
        </div>

        <%end%>

        <br />
        <br />

          <div class="row totals">
            <!--subtotalrow  -->
            <div class="col-md-2 col-xs-2"style="font-weight:bold;">
              <bold><u>Subtotal:</u></bold>
            </div>

            <div class="col-md-2 col-md-offset-1 col-xs-2 col-xs-offset-2">
              <p>
                <%=number_to_currency(subtotal)%>
              </p>
            </div>
          </div>
          <!--shippingrow  -->
          <div class="row">
            <div class="col-md-2 col-xs-2"style="font-weight:bold;">
              <bold><u>Shipping:</u></bold>
            </div>

            <div class="col-md-2 col-md-offset-1 col-xs-2 col-xs-offset-2">
              <p>
                <%=number_to_currency(15)%>
              </p>
            </div>
          </div>
          <!--grandtotal row  -->
          <div class="row">
            <div class="col-md-2 col-xs-2"style="font-weight:bold;">
              <bol><u>Grand Total</u></bold>
            </div>

            <div class="col-md-2 col-md-offset-1 col-xs-2 col-xs-offset-2">
              <p>
                <%=number_to_currency(subtotal+15)%>
              </p>
            </div>
          </div>

          </div>
        </div>


        <div class="container modal-cart-msg">
          <div class="row">
            <div class="col-md-6">

              <p>
                Please ensure your order and shipping address are correct. Ordering means you accept all terms of service. Once you submit your order, you will recieve an email with instructions on how to pay. We appreciate your business. Your product will arrive in 3-5 business days on confirmation of payment.
              </p>
            </div>
          </div>
        </div>

        <br />
        <br />
        <!--user address information -->
        <div class="container-fluid modal-cart-userinfo">
          <div class="row text-center">
            <h4>Your Shipping Information:</h4>
          </div>
          <div class="row">
            <div class="col-md-12">
              Name:<%=@user.full_name%>
            </div>
          </div>
          <br />


          <div class="row">
            <div class="col-md-12">
              <p>
                Address: <%=@user.address%>
              </p>
            </div>
            <div class="col-md-12">
              <p>
                Province: <%=@user.province%>
              </p>
            </div>
            <div class="col-md-12">
              <p>
                Postal code: <%=@user.postal_code%>
              </p>
            </div>
          </div>

          <br />
          <p>
            <%=@user.full_name%> is your shipping information correct? If it isn't you can edit your information <%=link_to 'here', edit_user_registration_path(@user)%>
          </p>
        </div>
        <br/>

      <div class="modal-footer">
        <div class="checkout-btn" id="modal-btn">
          <%=button_to "Confirm Order",new_order_path, {method: 'get', class: 'checkout'}%>
        </div>
      </div>
    </div>
    </div>
  </div>


<%end%>

app/views/carts/_form.html.erb
<%= form_for @cart_item, remote: true do |f| %>
  <div>
    <div class="input-group">
      <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
      <div class="input-group-btn">
        <%= f.hidden_field :product_id, value: product.id%>
        <%= f.submit "Add to Cart", class: "btn btn-primary"%>
      </div>
    </div>
  </div>
  <%end%>

app/views/carts/_test.html.erb
<h1>Shopping Cart</h1>
<%@cart.cart_items.each do |item|%>
<div class="shopping-cart">

  <div class="column-labels">
    <label class="product-image">Image</label>
    <label class="product-details">Product</label>
    <label class="product-price">Price</label>
    <label class="product-quantity">Quantity</label>
    <label class="product-removal">Remove</label>
    <label class="product-line-price">Total</label>
  </div>

  <div class="product">
    <div class="product-image">
      <%=image_tag(item.product.picture)%>
    </div>
    <div class="product-details">
      <div class="product-title"><%=item.product.name%></div>
      <p class="product-description"><%=item.product.description%></p>
    </div>
    <div class="product-price"><%=number_to_currency(item.product.price)%></div>
    <div class="product-quantity">
      <input type="number" value="2" min="1">
    </div>
    <div class="product-removal">
      <button class="remove-product">
        Remove
      </button>
    </div>
    <div class="product-line-price"><%=item.product.price*item.quantity%></div>
  </div>


</div>
<%end%>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

</br>
</br>

<div class="cart-container">
  <%=render 'carts_row'%>
</div>




</p>