config/routes.rb
  Rails.application.routes.draw do
  devise_for :users
  resources :orders, only: [:new, :index, :create, :show]
  resources :carts, only: [:show]

  resources :cart_items, only: [:create, :update, :destroy]

  resources :reviews
  root 'page#index'

  namespace :admin do
    resources :users
    resources :products
    resources :orders
  end

  resources :users, only: [:index, :new, :create, :show]
  resources :page, only: [:index, :post]

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  # validate :product_present
  validate :cart_present
  # need a new validation that doesn't mess up the product_id scope validations
  # was interfering with setting cart_item.cart_id = nil
# validates :cart_id, uniqueness:{ :scope => :product_id, :message => "Product already added." }

  before_save :finalize
  # a = CartItem.new; a.test_model test method for activerecord

  # def test_model
  #   return "It works"
  # end
  def empty_cart
    self.each do |item|
      item.cart_id = nil
      item.save!
    end
  end

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  def sub_total
    cart_items.collect {|item| item.valid? item.quantity * item.unit_price}.sum
  end

  private

  def product_present
    if product.nil?
      errors.add(:product, "Is not valid or is not active")
    end
  end

  def cart_present
    if cart.nil?
      errors.add(:cart, "is not a valid cart")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = total_price
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]
# scope for most_recent and subtotal
# find out if rails sorts on update column cuz this is annoying.


  def create
    # grabbing cart from application controller current_cart method
    @cart = current_cart
    # session[:cart_id] = @cart.id
    # individual product items get added to cart item and added to cart and saved
    @cart_item = @cart.cart_items.build(cart_item_params)
    @cart.save
  end

  def update
    @cart = current_cart
    # finding cart_items by cart_id
    @cart_item = @cart.cart_items.find(params[:id])
    # @cart_items.order(:id)
    @cart_item.update_attributes(cart_item_params)
    @cart_items = @cart.cart_items.order(:id)
    # redirect 'cart_show_path'
    @cart.save
  end

  def destroy
    @cart = current_cart
    @cart_item = @cart.cart_items.find(params[:id])
    @cart_item.destroy
    @cart_items = @cart.cart_items
    @cart.save
  end

  private
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    def cart_item_params
      params.require(:cart_item).permit(:cart_id, :product_id, :unit_price, :quantity, :total_price)
    end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_form.html.erb
<%= form_for(@cart_item, remote: true) do |f| %>
  <% if @cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% @cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.text_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :unit_price %><br>
    <%= f.text_field :unit_price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.number_field :total_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_items/create.html.erb
<h1>CartItems#create</h1>
<p>Find me in app/views/cart_items/create.html.erb</p>

app/views/cart_items/create.js.erb
<% if @cart.errors.any? || @cart_item.errors.any? %>
  alert("'<%=@cart_item.product.name%>' is already in your cart!.");
<%else%>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text')%>")
<%end%>

app/views/cart_items/destroy.js.erb
<% if @cart.errors.any? || @cart_item.errors.any? %>
  alert("Not valid.");
<%else%>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text')%>")
  $(".cart-container").html("<%= escape_javascript(render 'carts/carts_row')%>")
<%end%>

app/views/cart_items/edit.html.erb
<h1>Editing cart_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<h1>Listing cart_items</h1>

<table>
  <thead>
    <tr>
      <th>Cart</th>
      <th>Product</th>
      <th>Order</th>
      <th>Unit price</th>
      <th>Quantity</th>
      <th>Total price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.cart %></td>
        <td><%= cart_item.product %></td>
        <td><%= cart_item.order %></td>
        <td><%= cart_item.unit_price %></td>
        <td><%= cart_item.quantity %></td>
        <td><%= cart_item.total_price %></td>
        <td><%= link_to 'Show', cart_item %></td>
        <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
        <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New cart_item</h1>

<%= render 'form' %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cart:</strong>
  <%= @cart_item.cart %>
</p>

<p>
  <strong>Product:</strong>
  <%= @cart_item.product %>
</p>

<p>
  <strong>Order:</strong>
  <%= @cart_item.order %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @cart_item.unit_price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cart_item.quantity %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @cart_item.total_price %>
</p>

<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/update.js.erb
<% if @cart.errors.any? || @cart_item.errors.any? %>
  alert("Not valid.");
<%else%>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text')%>")
  $(".cart-container").html("<%= escape_javascript(render 'carts/carts_row')%>")
<%end%>