config/routes.rb
  Rails.application.routes.draw do
  devise_for :users
  resources :orders, only: [:new, :index, :create, :show]
  resources :carts, only: [:show]

  resources :cart_items, only: [:create, :update, :destroy]

  resources :reviews
  root 'page#index'

  namespace :admin do
    resources :users
    resources :products
    resources :orders
  end

  resources :users, only: [:index, :new, :create, :show]
  resources :page, only: [:index, :post]

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :picture, ProductImageUploader

  has_many :reviews
  has_many :cart_items, dependent: :destroy
  before_destroy :ensure_not_referenced_by_any_cart_item
  # has_and_belongs_to_many :cart_items

  #
  default_scope {where(active: true)}

  scope :searchName, -> (search) {where("lower(name) LIKE ?", "%#{search}%")}
  # scope :green, -> {where("category = ?", "1")}
  # scope :accessories, -> {where("category = ?", "2")}
  # scope :herbal, -> {where("cateogry = ?", "3")}


  private


    def ensure_not_referenced_by_any_cart_item
      if cart_items.empty?
        return true
      else
        errors.add(:base, "Cart Items present")
        return false
      end
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
before_filter :restricted_access

  def new
    @product = Product.new
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.create(admin_product_params)

    if @product
      flash[:alert] = "<%=@product.name%> successfully created."
      redirect_to admin_products_path
    else
      flash[:alert] = "Product was not successfully created."
      redirect_to new_admin_product_path
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(admin_product_params)
      flash[:alert] = "<%=@product.name}%> successfully saved."
      redirect_to admin_products_path
    # else
    #   render
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    # destroy product for admin namespace only.
    redirect_to admin_products_path
  end

  protected

  def admin_product_params
    params.require(:product).permit(:category, :name, :description, :price, :picture, :featured, :active)
  end

end

app/controllers/products_controller.rb
class ProductsController<ApplicationController
before_filter :authenticate_user!


  def index
    # current_cart's cart_items.new
    @cart_item = current_cart.cart_items.new
    # params[:search] from the header :search_bar

    # if the search is enter with nil then it should return all products
    if params[:search] == "" || params[:search].nil?
      @products = Product.all

    # else downcase the search value and pass the params to products model to search for products
    else
      params[:search] = params[:search].downcase
      @products = Product.searchName(params[:search])
    end
  end

  def show
    @cart_item = current_cart.cart_items.new
    @product = Product.find(params[:id])
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="container">
<%=form_for([:admin, @product], html:{role: 'form'}) do |f| %>

  <% if @product.errors.any? %>
    <div>
    <%= pluralize(@product.errors.count, "errors") %> prevented the product from being created:
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
  <%end%>


    <em><bold>Enter new information:</bold></em>

        <div class="form-group">
          <%= f.label :category%>
          <%= f.number_field :category, min: 1, max: 3%> 1)Green, 2)Accessories, 3) Herbal<br/>
        </div>


        <div class="form-group">
          <%= f.label :name%>
          <%= f.text_field :name, class: 'form-control'%><em> What the product should be named.</em><br/>
        </div></br>


        <div class="form-group">
          <%= f.label :price %>
          <%= f.number_field :price, class: 'form-control'%><em> The price of the product</em><br/>
        </div>


        <div class="form-group">
          <%= f.label :picture %>
          <%= f.file_field :picture, class: 'form-control'%><em> The picture of the product </em>
        </div>


        <div class="form-group">
          <%= f.label :description%>
          <%= f.text_area :description,  class: 'form-control', rows: 5 %><br/>
        </div>


        <div class="form-group">
          <div class="row">
              <div class="col-md-2">
                <%= f.label :active %>
                <%= f.check_box :active %>
              </div>

              <div class="col-md-2">
                <%= f.label :featured %>
                <%= f.check_box :featured %>
              </div>
          </div>
        </div>



        <div class="form-group">
          <%=f.submit "Save", data: {confirm: "Are you sure you want to save these changes?"}%>
        </div>
      </li>
    <%end%>
  </ul>
</div>

app/views/admin/products/edit.html.erb
<div class="container">

  <ul style="list-style: none; margin-top: 100px;">
    <div class="row">
      <div class="img-responsive">
        <div class="thumbnail">
          <img src="<%=@product.picture%>">
        </div>
      </div>
    </div>
  </ul>
</div>


</br>

<%=render 'form'%>

app/views/admin/products/index.html.erb
<h1 class="text-center">Admin Panel</h1>

<div class="container">
  <div class="row text-center">
    <button><%=link_to 'Add new product', new_admin_product_path%></button>
    <button><%=link_to 'Orders', admin_orders_path%></button>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="img-responsive">

    <% @products.each do |product| %>
        <div class="col-md-3">
      <%if product.active == true%>
           <div class="thumbnail" style="background-color: green">
      <%elsif product.active == false%>
           <div class="thumbnail" style="background-color: red">
      <%end%>
             <%=link_to image_tag(product.picture), edit_admin_product_path(product)%>
              Product Name:<%=product.name%> <button><%=link_to 'Edit', edit_admin_product_path(product)%></button><button><%=link_to 'Delete', admin_product_path(product), method: :delete, data: {confirm: "Are you sure you want to delete this product?" }%>
          </div>
        </div>
      <%end%>

    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<h1 class="text-center">Add a new product to the store</h1>

<%=render 'form'%>